title: "Ece Calikus"
description: "Assistant Professor of Computer Science Â· Uppsala University"
url: "https://reguluslus.github.io"

theme: minima

minima:
  skin: auto

header_pages:
  - research.md
  - publications.md
  - teaching.md
  - students.md
  - cv.md

author:
  name: "Ece Calikus"
